Website endpoint
termly/apidocs pull request #5
Opened 2021-09-21 13:57 UTC by josh-termly

* Document The website endpoint
* Start documenting errors

2021-09-21 15:03 UTC, dkreft-termly requested changes

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites.md
> +Websites represent a single website and stores the settings that controls compliance, cookie consent, banner styling, etc.  Almost all enpoint calls will reference a website in someway.
"Websites represent a single website and each stores..."

"...will reference a website in some way."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_delete.md
> +If the entire request is in error or invalid the result JSON will be [error object](../error_object.md#universal-errors)
"...or invalid, ..."  (comma after "invalid")

"...will be an [error object]..."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_delete.md
> +    "_idx": 0,
There should be an explicit call-out regarding `_foo` data in general, and `_idx` in particular...probably in the "Overview" section.

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +at least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  Once constructed the must be URL encoded and be th
"At least..."

What will happen if `ids` is empty?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +`results` will be 0 or more of this object:
"...0 or more objects with this shape:"

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +}
I'd like to encourage you to sort the keys in each object....same with the bullet list, below.

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `account_id` unique identifier of the account that owns the website
Should we not also include the data type of each datum?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `scan_period` howe often the website will be scanned
"how"

What are the units? Milliseconds? Seconds? Months? Days? Years?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `subdomains` an array of subdomains that the scanner should scan as ell
hell? smell? bell? tell? *well*?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  * items should be strings
Should be? Or will be?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  * `address` street address of the company
Might want to include an `address2`. I'm not sure what kind of addresses need it, but it seems to be pretty much ubiquitous in address forms I've seen.

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  * `country` country
I'm not sure that the explanatory text is necessary or helpful; the keys are self-documenting.

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `code_snippet` object that contains Javascript snippets to install termly on the website
JavaScript :-)

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +multiple accounts and websites in each account and one website cannot be found
"Multiple..."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
The more I see of this, the more nervous I get that we're going to run into URL length limitations. This is a very, very verbose way to request this data. :-(

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_post.md
> +The body must have 1 or more of these objects.  Once created the JSON must be passed as the request body
"Once created, the..."

"...request body." (missing period)

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_post.md
> +]
TODO?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_post.md
> +  "_idx": "<string>"
Why is GitHub making your colon red? (Huh huh heh heh mm mm heh...he said "colon").

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_post.md
> +## Request
Add blank line between LL88,89

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_post.md
> +submit multiple websites one of which has a validation error
"Submit multiple websites, one of which...error."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +The body must have 1 or more of these objects. Any attributes not passed in will not be changed.  Once created the JSON must be passed as the request body
"Once created, ..."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +]
TODO?

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +  "_idx": "<string>"
Heh heh mm mm heh...colon.

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +If the entire request is in error or invalid the result JSON will be [error object](../error_object.md#universal-errors)
"...or invalid, ..."

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +## Request
Blank line betwixt

2021-09-21 15:03 UTC, dkreft-termly commented on endpoints/websites_put.md
> +submit multiple websites one of which does not exist
"Submit multiple websites, one of which does not exist."

(comma, period)

2021-09-21 15:03 UTC, dkreft-termly commented on error_object.md
> +# Get Errors
"GET"

2021-09-21 15:03 UTC, dkreft-termly commented on error_object.md
> +Universal errors accour when the entire request is in error or unrecoverable. The JSON is formed as shown:
"accour"??

2021-09-21 15:03 UTC, dkreft-termly commented on error_object.md
> +## To Many Items
To where? I think you mean "Too." :-)

2021-09-21 15:03 UTC, dkreft-termly commented on error_object.md
> +  "error": "to_many_items"
too

2021-09-21 15:03 UTC, dkreft-termly commented on error_object.md
> +## In correct API key
"Incorrect"

2021-09-21 16:51 UTC, josh-termly commented on endpoints/websites_delete.md
> +    "_idx": 0,
will add to `README.md` as it applies to the entire API

2021-09-21 17:02 UTC, ghost reviewed
I'm good with Dan changes too

2021-09-21 17:02 UTC, ghost commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
this same thing occurred to me, then I read this: https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string

I think we are asking for trouble regardless, but The Internet At Large seems to be mostly comfortable. Ted and Gino would raise hell I'm guessing...

2021-09-21 17:51 UTC, josh-termly commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
it is not great, but we are limiting the number of items they can request at once.  So I think we can safely keep it to 2048K (as recommended).  However, I am open to ideas.

2021-09-21 17:53 UTC, josh-termly commented on endpoints/websites_get.md
> +}
can we hold off sorting until we have the API approved from Access Group and know we are not going to do any major changes?

2021-09-21 17:54 UTC, josh-termly commented on endpoints/websites_get.md
> +* `account_id` unique identifier of the account that owns the website
I believe that they are in lines 33 to 64

2021-09-21 17:57 UTC, josh-termly commented on endpoints/websites_get.md
> +  * `country` country
These keys are self documenting but not all of the keys in the API are so I would lean to keeping them in for consistency.

2021-09-21 17:58 UTC, josh-termly commented on endpoints/websites_get.md
> +  * `address` street address of the company
I know this is small but I would say anything that is not required we keep out for now to keep the scope as tight as possible considering the deadlines

2021-09-21 17:59 UTC, josh-termly commented on endpoints/websites_post.md
> +]
represented by the object below.  We could combine the 2 if that is preferred.

2021-09-21 18:01 UTC, josh-termly commented on endpoints/websites_put.md
> +]
object is below

2021-09-22 18:04 UTC, dkreft-termly requested changes

2021-09-22 18:04 UTC, dkreft-termly commented on README.md
> +* Attributes that start with `_` are meta attributes that are not related to the action the API is performing
I'd remove the asterisk here...it's not really a part of the bullet list...at least not on the same level as that which follows (the following line, if anything, is a detail reinforcing L10).

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites.md
> +Websites represent a single website and each stores the settings that controls compliance, cookie consent, banner styling, etc.  Almost all endpoint calls will reference a website in some way.
English is dumb.

"...settings that control..."  (the settings control, it's not the website that controls)

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +At least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  if `ids` is sent it must have 1 or more items. Onc
Third sentence should start with "If" not "if."

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +At least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  if `ids` is sent it must have 1 or more items. Onc
Also, the last sentence is screaming for an actual example. A picture is worth a thousand words.

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +}
I'm not sure why sorting should be contingent upon what AG says. I would think that if you're going to present this to AG, then it should be as readable as possible...but, okay.

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `account_id` unique identifier of the account that owns the website
🤦

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  "consent_count": "<integer>",
This is confusing....you say integer, but it's wrapped in quotes. This communicates to me that the server is expecting to receive a string, not an integer.

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  * items should be strings
Unaddressed.

When you say "should," it implies "wiggle room."

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +  * `address` street address of the company
Easy enough to add later, I suppose.

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +* `code_snippet` object that contains Javascript snippets to install termly on the website
*cough* Unaddressed. The "s" really should be capitalized.

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
I would prefer a more normalized data structure, but that's difficult if we're going to be allowing requests to span `account_id`s. :-\

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_post.md
> +]
I think I would just combine the two:

```
[
  {
    "account_id": "<string>",
    // etc.
  }
]
```

2021-09-22 18:04 UTC, dkreft-termly commented on endpoints/websites_put.md
> +]
See my response above.

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +### Response
Remove...unnecessary and inconsistent.

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +* `validation_errors` array of validation errors, only returned when code is **validation_error**
The bold text is confusing. If you're representing an actual value, I'd think it'd be more appropriate to use

```markdown
`"validation_error"`
```

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +  * `field` the attribute of the object that caused this validation failure. If the validation failure is general to the object this will be **object**
ditto

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +### Response
Again, I don't think a "Response" subheader is necessary or useful here.

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +### Response
Nix. Same throughout this document.

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +* `validation_errors` array of validation errors, only returned when code is **validation_error**
Afterthought...I wonder if this shouldn't be `"validation_errors"` (note the plural) so that there's consistency with the datum that contains the errors?

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +  "validation_errors": [
See L51, which states that this key will only exist when `{ error: "validation_error" }`

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +      "message": "must be unique"
We need to include an `error` not a `message`. This is going to make i18n very difficult.

2021-09-22 18:04 UTC, dkreft-termly commented on error_object.md
> +The API key does not have the correct role to complete 1 or more of the requested actions. Even if some of the requests would have been successful if 1 of the requests is not authorized the entire re
The second sentence should probably say "one" instead of "1."

2021-09-22 19:50 UTC, justrudd commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
We're following the pattern of GraphQL (https://graphql.org/learn/serving-over-http/#get-request). Queries for `GET` are passed in the query string. The main difference being we are using JSON not our own query language.

2021-09-22 19:57 UTC, justrudd commented on endpoints/websites_get.md
> +GET https://api.termly.io/v1/websites?query=%5B%20%7B%20%22account_id%22%3A%20%22acct_123%22%2C%20%22ids%22%3A%20%5B%22web_123%22%5D%7D%2C%20%7B%22account_id%22%3A%20%22acct_1234%22%2C%20%22ids%22%3A
If we want to come up with our own query language, we can. But it's still going to be encoded and passed in a query string parameter. And there would be no tools for generating it. I picked a format that everyone knows and doesn't require us to write a client.

2021-09-22 19:58 UTC, justrudd commented on endpoints/websites_get.md
> +  "uuid": "<string>",
We `id`. Don't need `uuid` as well.

2021-09-22 20:00 UTC, justrudd commented on endpoints/websites_get.md
> +  "consent_count": "<integer>",
Probably because of syntax highlighting. If you don't wrap it in quotes, it looks like this.

<img width="343" alt="Screen Shot 2021-09-22 at 12 59 10 PM" src="https://user-images.githubusercontent.com/7537582/134413312-65918a0f-3d14-4e48-8051-52994b0f7157.png">

But I agree with Dan. I'd rather it be correct. So remove the quotes.

2021-09-22 20:00 UTC, justrudd commented on endpoints/websites_get.md
> +  "consent_count": "<integer>",
Or remove the language identifier and just let it be monospace font.

2021-09-22 20:33 UTC, josh-termly commented on endpoints/websites_get.md
> +At least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  if `ids` is sent it must have 1 or more items. Onc
If you mean encoding of the parameters needs an example each example has the encoded and non encoded parameters

2021-09-23 15:52 UTC, dkreft-termly approved these changes

2021-09-23 15:52 UTC, dkreft-termly commented on endpoints/websites_get.md
> +At least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  If `ids` is sent it must have 1 or more items. Onc
What should happen if the array is empty?

2021-09-23 15:52 UTC, dkreft-termly commented on error_object.md
> +  * `error` validation error code f
"f"?

2021-09-24 02:39 UTC, ghost approved these changes
LGTM

2021-09-24 03:18 UTC, josh-termly commented on endpoints/websites_get.md
> +At least 1 object with an `account_id` must be provided.  If you would like to retrieve all of the websites in an account omit the `ids` parameter.  If `ids` is sent it must have 1 or more items. Onc
added example

2021-09-24 03:19 UTC, merged