Update collaborator endpoints
termly/apidocs pull request #9
Opened 2021-09-22 19:39 UTC by justrudd

2021-09-22 21:37 UTC, ghost requested changes
couple of minor things

2021-09-22 21:37 UTC, ghost commented on endpoints/delete_collaborators.md
> +At least 1 object with the field `account_id` is required. Once the query is constructed, it is passed in the query string parameter `query`. It must be URL encoded.
Doesn't the DELETE verb put the data in the body of the request?

2021-09-22 21:37 UTC, ghost commented on endpoints/post_collaborators.md
> +	"_idx": <integer>,
technically this should be <number>

2021-09-22 23:41 UTC, justrudd commented on endpoints/post_collaborators.md
> +	"_idx": <integer>,
Should be? Your comment kind of cuts off...

2021-09-22 23:42 UTC, justrudd commented on endpoints/post_collaborators.md
> +	"_idx": <integer>,
`<Integer>`? Uppercase I?

2021-09-22 23:48 UTC, justrudd commented on endpoints/delete_collaborators.md
> +At least 1 object with the field `account_id` is required. Once the query is constructed, it is passed in the query string parameter `query`. It must be URL encoded.
It's ambiguous. The spec doesn't allow nor forbid it. Supposedly the next version of the spec will have this text in it:

> A client SHOULD NOT generate a body in a DELETE request. A payload received in a DELETE request has no defined semantics, cannot alter the meaning or target of the request, and might lead some implementations to reject the request.

And I have run across HTTP libraries in the past that don't allow `DELETE` to have a body.

2021-09-23 12:56 UTC, josh-termly commented on endpoints/delete_collaborators.md
> +At least 1 object with the field `account_id` is required. Once the query is constructed, it is passed in the query string parameter `query`. It must be URL encoded.
which why do we want to go? If we do want them in the query params then Steve and I will need to update our PRs

2021-09-23 12:56 UTC, josh-termly commented on endpoints/post_collaborators.md
> +If one of the collaborators cannot be created, the object will be an [error object](../error_object.md). If the error is a validation error, there will be a field called [validation errors](../valida
When I filled in the error details I put them all in the `error_object.md` if we want to operate them into separate files let me know.

2021-09-23 12:56 UTC, josh-termly commented on endpoints/put_collaborators.md
> +* `role` is one of the following values - `admin`, `owner`, or `editor`. Please see [here](collaborator_roles.md) for details.
will there be another PR for `collaborator_roles.md`?

2021-09-23 15:35 UTC, ghost commented on endpoints/post_collaborators.md
> +	"_idx": <integer>,
never mind, JSON adds an  integer type over JavaScript's number type.

https://json-schema.org/understanding-json-schema/reference/numeric.html

2021-09-23 17:32 UTC, justrudd commented on endpoints/delete_collaborators.md
> +At least 1 object with the field `account_id` is required. Once the query is constructed, it is passed in the query string parameter `query`. It must be URL encoded.
@josh-termly query string. The spec is ambiguous so we go with what we know works.

2021-09-23 17:33 UTC, justrudd commented on endpoints/post_collaborators.md
> +If one of the collaborators cannot be created, the object will be an [error object](../error_object.md). If the error is a validation error, there will be a field called [validation errors](../valida
@josh-termly - one file is fine. Once your PR with the definitions get merged, I'll update this.

2021-09-23 17:34 UTC, justrudd commented on endpoints/put_collaborators.md
> +* `role` is one of the following values - `admin`, `owner`, or `editor`. Please see [here](collaborator_roles.md) for details.
Yes. I'll do that one later. It's not critical path for getting them out the door

2021-09-23 17:35 UTC, merged